Insert current year into license
forcedotcom/dev-scripts pull request #35
Opened 2021-11-23 19:56 UTC by iowillhoit

`sf-install` makes sure that the `LICENSE.txt` file is included in your repo. This PR inserts the current year into the license. 

[@W-10222138@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10222138)

## Testing Instructions
- Pull this branch
- Run `yarn link`
- `cd` to another plugin that uses `sf-install` (I used `plugin-command-reference` 🤷)
- Run `yarn link @salesforce/dev-scripts`
- Run `yarn`
- The `LICENSE.txt` file will now have 2021 (instead of 2018)
- Cleanup: run `yarn unlink @salesforce/dev-scripts`

2021-11-23 22:30 UTC, cristiand391 requested changes
QA notes:
(plugin-source)

✅ LICENCE file was updated after running `yarn install`
❌ Can see message `adding config files` when LICENSE file is updated.
❌ Can see message `adding config files` if LICENSE file doesn't exists and is created.

@iowillhoit when `writeLicenseFile` writes the file it returns the path to LICENSE to its caller in [`utils/standarize-files.js:83`](https://github.com/forcedotcom/dev-scripts/blob/adbb0f043cd0c58c7cd4b3933c606abe74f17413/utils/standardize-files.js#L83). You may want to use `copyFile` instead of `writeFileSync`.

2021-11-24 19:05 UTC, RodEsp approved these changes

2021-11-29 18:21 UTC, iowillhoit commented
Good catch @cristiand391, updated to use `copyFile`

2021-11-29 19:56 UTC, cristiand391 approved these changes
:shipit:

2021-11-29 20:27 UTC, merged